// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The app's real runtime database (see lib/prisma.ts) is the local
    // SQLite file, not DATABASE_URL (that env var points at an unused
    // Postgres instance — a pre-existing loose end, left as-is).
    url: "file:./dev.db",
  },
});
