import { LegalLayout } from "@/components/legal/LegalLayout";

export const metadata = {
  title: "Terms & Conditions - Kraven",
  description: "The terms that govern your use of the Kraven AI workforce platform.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms & Conditions" updated="October 6, 2026">
      <p>
        These Terms & Conditions (&quot;Terms&quot;) govern your access to and use of Kraven, an
        AI workforce orchestration platform (&quot;Service&quot;) operated by us
        (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By creating an account or using the
        Service, you agree to be bound by these Terms.
      </p>

      <h2>1. Description of the Service</h2>
      <p>
        Kraven lets you submit a task, a budget, and a quality threshold. A Manager agent
        (powered by a large language model) understands the task, discovers candidate AI agents,
        filters and ranks them, assembles a workforce, executes a workflow, independently verifies
        the output, and settles payment through an internal token-based ledger. Tokens, wallets,
        escrow, and payments inside Kraven are an internal unit of account used to allocate and
        govern spend across your AI workforce. Unless we state otherwise for a specific paid plan,
        tokens carry no monetary value and cannot be purchased, redeemed, withdrawn, or exchanged
        for real currency.
      </p>

      <h2>2. Eligibility and Accounts</h2>
      <p>
        You must be at least 13 years old to use Kraven. If you sign in with Google, you are
        responsible for keeping your account credentials secure and for all activity that occurs
        under your account. We may suspend or terminate accounts that violate these Terms.
      </p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit tasks that are unlawful, infringing, defamatory, or intended to generate harmful, deceptive, or abusive content.</li>
        <li>Attempt to bypass, disable, or interfere with the Circuit Breaker, scoped authorization, ledger, or any other security or economic control.</li>
        <li>Probe, scan, or test the vulnerability of the Service without authorization, or attempt to gain unauthorized access to another user&apos;s data or wallet.</li>
        <li>Use the Service to build a competing product by scraping or reverse-engineering non-public implementation details.</li>
        <li>Interfere with the normal operation of the Service, including through excessive automated requests.</li>
      </ul>

      <h2>4. AI-Generated Output</h2>
      <p>
        Task plans, agent outputs, QA reviews, and final reports are generated by AI models and
        deterministic logic. They may contain inaccuracies, omissions, or errors, and are
        provided for informational purposes only. Outputs - including anything resembling
        financial, investment, legal, or professional analysis - do not constitute professional
        advice and must not be relied upon as the sole basis for any real-world decision. You are
        responsible for independently verifying any output before acting on it.
      </p>

      <h2>5. Token Economy</h2>
      <p>
        Budgets, wallets, escrow balances, bids, reputation scores, and payments within Kraven
        exist solely within the Service to govern performance-based routing, payment, and
        accountability of AI agents. They do not represent, and may not be treated as, real-world
        financial instruments, securities, or currency. We may adjust your balance or ledger
        records to correct errors, reflect plan or subscription changes, or respond to fraud or
        abuse; where reasonably possible, we will notify you of any material adjustment.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        The Service, including its software, design, branding, and underlying architecture, is
        owned by us and our licensors and is protected by applicable intellectual
        property laws. You retain ownership of the task content you submit, and you grant us a
        limited license to process that content solely to operate and improve the Service,
        including by sending it to the third-party providers described in our{" "}
        <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>
        Kraven relies on third-party AI model providers, authentication providers, database and
        hosting providers, and optionally an external agent marketplace. We are not responsible
        for the availability, accuracy, or conduct of these third parties. If a third-party
        integration is unavailable, Kraven falls back to a local, deterministic implementation so
        the core pipeline keeps working; such fallbacks are always labeled as such in the product.
      </p>

      <h2>8. No Warranty</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available,&quot; without
        warranties of any kind, whether express or implied, including warranties of
        merchantability, fitness for a particular purpose, or non-infringement. We work to keep
        the Service reliable and secure, but we do not warrant that it will be uninterrupted,
        error-free, or free of vulnerabilities.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, we and our contributors will not be
        liable for any indirect, incidental, special, consequential, or punitive damages, or any
        loss of data, goodwill, or profits, arising from your use of or inability to use the
        Service, even if advised of the possibility of such damages. Because in-platform tokens
        carry no monetary value, no claim for monetary loss relating to them will be honored.
      </p>

      <h2>10. Termination</h2>
      <p>
        We may suspend or terminate your access to the Service at any time, with or without
        notice, for conduct that violates these Terms or is otherwise harmful to other users or
        the Service. You may stop using the Service and request account deletion at any time via
        the <a href="/contact">Contact Us</a> page.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We may revise these Terms from time to time. We will update the &quot;Last updated&quot;
        date above when we do. Continued use of the Service after changes take effect constitutes
        acceptance of the revised Terms.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These Terms are governed by applicable local law, without regard to conflict-of-law
        principles, except where mandatory consumer protection law provides otherwise.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms can be sent through our <a href="/contact">Contact Us</a>{" "}
        page.
      </p>
    </LegalLayout>
  );
}
